// extension/src/webviews/app/components/ui/input.tsx
import * as React from 'react';
import { cn } from '../../lib/utils';

export type InputProps = React.InputHTMLAttributes<HTMLInputElement>;

const Input = React.forwardRef<HTMLInputElement, InputProps>(
  ({ className, type = 'text', onFocus, ...props }, ref) => {
    const handleFocus: React.FocusEventHandler<HTMLInputElement> = (event) => {
      // Mirror React version's placeholder logging hook where we could
      // later send a WebviewFocusChanged command if desired.
      // eslint-disable-next-line no-console
      console.log(
        'Input focused - Ready to send WebviewFocusChangedCommand if needed'
      );

      onFocus?.(event);
    };

    return (
      <input
        ref={ref}
        type={type}
        className={cn(
          'vscode-input',
          'text-[13px] leading-[1.4] rounded-[2px] border border-[color:var(--vscode-input-border,transparent)]',
          'px-2 py-[6px] font-sans outline-none transition-colors',
          'text-[color:var(--vscode-input-foreground)]',
          'bg-[color:var(--vscode-input-background)]',
          'placeholder:text-[color:var(--vscode-input-placeholderForeground)]',
          'focus:border-[color:var(--vscode-focusBorder)]',
          'focus:outline focus:outline-[1px] focus:outline-[color:var(--vscode-focusBorder)] focus:outline-offset-[-1px]',
          'disabled:opacity-50 disabled:cursor-not-allowed',
          className
        )}
        onFocus={handleFocus}
        {...props}
      />
    );
  }
);

Input.displayName = 'Input';

export { Input };

// extension/src/webviews/app/components/ui/input/input.svelte
<script lang="ts">
  import type { HTMLAttributes } from "svelte/elements";
  import { cn } from "../../../lib/utils.js";

  type $$Props = HTMLAttributes<HTMLInputElement>;

  let className: $$Props["class"] = undefined;
  export { className as class };
  export let value: string = "";
  export let inputType: string = "text";
  export let placeholder: string = "";
  export let disabled: boolean = false;

  function handleFocus() {
    console.log('Input focused - Ready to send WebviewFocusChangedCommand if needed');
  }
</script>

<input
  bind:value
  type={inputType}
  {placeholder}
  {disabled}
  class={cn(
    "vscode-input",
    className
  )}
  on:focus={handleFocus}
  {...$$restProps}
/>

<style>
  .vscode-input {
    color: var(--vscode-input-foreground);
    background-color: var(--vscode-input-background);
    border: 1px solid var(--vscode-input-border, transparent);
    padding: 6px 8px;
    border-radius: 2px;
    font-size: 13px;
    font-family: var(--vscode-font-family);
    line-height: 1.4;
    outline: none;
    transition: border-color 0.1s ease;
  }
  
  .vscode-input:focus {
    border-color: var(--vscode-focusBorder);
    outline: 1px solid var(--vscode-focusBorder);
    outline-offset: -1px;
  }
  
  .vscode-input::placeholder {
    color: var(--vscode-input-placeholderForeground);
  }
  
  .vscode-input:disabled {
    opacity: 0.5;
    cursor: not-allowed;
  }
  
  .vscode-input::selection {
    background-color: var(--vscode-input-selectionBackground);
    color: var(--vscode-input-selectionForeground);
  }
</style>
