// extension/src/webviews/app/components/CommandPaletteTest.tsx
import { useState, useMemo, useCallback } from 'react';
import { useIpc } from '../contexts/ipc';
import type { IpcScope } from '../../protocol';
import {
  Command,
  CommandInput,
  CommandList,
  CommandEmpty,
  CommandGroup,
  CommandSeparator,
  CommandItem,
} from '../components/ui/command';

interface PaletteCommand {
  label: string;
  description: string;
  action: {
    command: string;
    params?: Record<string, unknown>;
    scope: IpcScope;
  };
}

const fileCommands: PaletteCommand[] = [
  {
    label: 'New File',
    description: 'Create a new file',
    action: {
      command: 'webview/execute-command',
      params: { command: 'workbench.action.files.newUntitledFile' },
      scope: 'webview-mgmt',
    },
  },
  {
    label: 'Save File',
    description: 'Save the current file',
    action: {
      command: 'webview/execute-command',
      params: { command: 'workbench.action.files.save' },
      scope: 'webview-mgmt',
    },
  },
];

const sampleCommands: PaletteCommand[] = [
  {
    label: 'Open File',
    description: 'Open a file in the editor',
    action: {
      command: 'file/open',
      params: { uri: 'file:///example.txt', line: 1 },
      scope: 'qdrantIndex',
    },
  },
  {
    label: 'Search',
    description: 'Search for files',
    action: {
      command: 'search',
      params: { query: 'test' },
      scope: 'qdrantIndex',
    },
  },
  {
    label: 'Settings',
    description: 'Open extension settings',
    action: {
      command: 'webview/execute-command',
      params: {
        command: 'workbench.action.openSettings',
        args: ['mcpFsServer'],
      },
      scope: 'webview-mgmt',
    },
  },
];

export default function CommandPaletteTest() {
  const ipc = useIpc();

  const [isVisible, setIsVisible] = useState(true);
  const [searchQuery, setSearchQuery] = useState('');
  const [selectedValue, setSelectedValue] = useState('');

  const allCommands = useMemo(
    () => [...fileCommands, ...sampleCommands],
    []
  );

  const ipcAvailable = Boolean(ipc);

  const toggleVisibility = useCallback(() => {
    setIsVisible((v) => !v);
  }, []);

  const handleSelect = useCallback(
    (value: string) => {
      setSelectedValue(value);

      const cmd = allCommands.find((c) => c.label === value);
      if (!cmd) {
        // eslint-disable-next-line no-console
        console.warn('No command found for value:', value);
        return;
      }

      ipc.sendCommand(cmd.action.command, cmd.action.scope, cmd.action.params ?? {});
    },
    [allCommands, ipc]
  );

  const filteredFileCommands = useMemo(
    () =>
      fileCommands.filter((cmd) =>
        cmd.label.toLowerCase().includes(searchQuery.toLowerCase())
      ),
    [searchQuery]
  );

  const filteredSampleCommands = useMemo(
    () =>
      sampleCommands.filter((cmd) =>
        cmd.label.toLowerCase().includes(searchQuery.toLowerCase())
      ),
    [searchQuery]
  );

  return (
    <div className="p-5 min-h-screen font-sans text-[13px] bg-[color:var(--vscode-editor-background)] text-[color:var(--vscode-foreground)]">
      <h2 className="text-base font-semibold mb-3">
        Command Palette Component Test
      </h2>

      <div className="flex items-center gap-4 mb-5">
        <button
          type="button"
          onClick={toggleVisibility}
          className="px-4 py-2 rounded bg-[color:var(--vscode-button-background)] text-[color:var(--vscode-button-foreground)] text-xs"
        >
          {isVisible ? 'Hide' : 'Show'} Command Palette
        </button>
        <div className="text-xs text-[color:var(--vscode-descriptionForeground)]">
          IPC Context: {ipcAvailable ? '✅ Available' : '❌ Not Available'}
        </div>
      </div>

      {isVisible && (
        <Command
          value={selectedValue}
          onValueChange={handleSelect}
          filter={() => 1}
        >
          <CommandInput
            value={searchQuery}
            onValueChange={setSearchQuery}
            placeholder="Type a command or search..."
          />

          <CommandList>
            <CommandEmpty>
              {searchQuery
                ? `No commands found for "${searchQuery}"`
                : 'No commands available'}
            </CommandEmpty>

            <CommandGroup heading="File Operations">
              {filteredFileCommands.map((cmd) => (
                <CommandItem
                  key={cmd.label}
                  value={cmd.label}
                  onSelect={() => handleSelect(cmd.label)}
                >
                  <div className="flex flex-col gap-0.5">
                    <div className="font-medium">{cmd.label}</div>
                    <div className="text-[11px] text-[color:var(--vscode-descriptionForeground)]">
                      {cmd.description}
                    </div>
                  </div>
                </CommandItem>
              ))}
            </CommandGroup>

            <CommandSeparator />

            <CommandGroup heading="Extension Commands">
              {filteredSampleCommands.map((cmd) => (
                <CommandItem
                  key={cmd.label}
                  value={cmd.label}
                  onSelect={() => handleSelect(cmd.label)}
                >
                  <div className="flex flex-col gap-0.5">
                    <div className="font-medium">{cmd.label}</div>
                    <div className="text-[11px] text-[color:var(--vscode-descriptionForeground)]">
                      {cmd.description}
                    </div>
                  </div>
                </CommandItem>
              ))}
            </CommandGroup>
          </CommandList>
        </Command>
      )}

      <div className="mt-5 px-4 py-3 rounded border-l-4 border-[color:var(--vscode-textBlockQuote-border)] bg-[color:var(--vscode-textBlockQuote-background)]">
        <h3 className="font-medium mb-2 text-[13px]">Test Information</h3>
        <p className="text-xs mb-1">
          <strong>Selected Value:</strong> {selectedValue || 'None'}
        </p>
        <p className="text-xs mb-2">
          <strong>Search Query:</strong> {searchQuery || 'None'}
        </p>
        <p className="text-xs mb-1">
          <strong>Components Tested:</strong>
        </p>
        <ul className="list-disc list-inside text-xs space-y-1">
          <li>Command (container)</li>
          <li>CommandInput (search input)</li>
          <li>CommandList (results)</li>
          <li>CommandItem (command entries with IPC wiring)</li>
          <li>CommandGroup (grouped sections)</li>
          <li>CommandSeparator</li>
          <li>CommandEmpty</li>
        </ul>
      </div>
    </div>
  );
}

// extension/src/webviews/app/components/CommandPaletteTest.svelte
<script lang="ts">
  import Command from './ui/command/command.svelte';
  import CommandInput from './ui/command/command-input.svelte';
  import CommandList from './ui/command/command-list.svelte';
  import CommandItem from './ui/command/command-item.svelte';
  import CommandGroup from './ui/command/command-group.svelte';
  import CommandSeparator from './ui/command/command-separator.svelte';
  import CommandEmpty from './ui/command/command-empty.svelte';
  import { getIpcContext } from '../contexts/ipc';
  import type { IpcScope } from '../../../protocol';

  let isVisible = $state(true);
  let searchQuery = $state('');
  let selectedValue = $state('');

  // Sample command data for testing
  const sampleCommands = [
    {
      label: 'Open File',
      description: 'Open a file in the editor',
      action: {
        command: 'file/open',
        params: { uri: 'file:///example.txt', line: 1 },
        scope: 'qdrantIndex' as IpcScope
      }
    },
    {
      label: 'Search',
      description: 'Search for files',
      action: {
        command: 'search',
        params: { query: 'test' },
        scope: 'qdrantIndex' as IpcScope
      }
    },
    {
      label: 'Settings',
      description: 'Open extension settings',
      action: {
        command: 'webview/execute-command',
        params: { command: 'workbench.action.openSettings', args: ['mcpFsServer'] },
        scope: 'webview-mgmt' as IpcScope
      }
    }
  ];

  const fileCommands = [
    {
      label: 'New File',
      description: 'Create a new file',
      action: {
        command: 'webview/execute-command',
        params: { command: 'workbench.action.files.newUntitledFile' },
        scope: 'webview-mgmt' as IpcScope
      }
    },
    {
      label: 'Save File',
      description: 'Save the current file',
      action: {
        command: 'webview/execute-command',
        params: { command: 'workbench.action.files.save' },
        scope: 'webview-mgmt' as IpcScope
      }
    }
  ];

  function handleCommandSelect(value: string) {
    selectedValue = value;
    console.log('Command selected:', value);
  }

  function toggleVisibility() {
    isVisible = !isVisible;
  }

  // Test IPC context availability
  let ipcAvailable = $state(false);
  try {
    const ipc = getIpcContext();
    ipcAvailable = true;
  } catch (error) {
    console.warn('IPC context not available:', error);
  }
</script>

<div class="test-container">
  <h2>Command Palette Component Test</h2>
  
  <div class="test-controls">
    <button onclick={toggleVisibility}>
      {isVisible ? 'Hide' : 'Show'} Command Palette
    </button>
    <div class="status">
      IPC Context: {ipcAvailable ? '✅ Available' : '❌ Not Available'}
    </div>
  </div>

  {#if isVisible}
    <Command bind:value={selectedValue} isVisible={isVisible} on:change={(e) => handleCommandSelect(e.detail)}>
      <CommandInput bind:query={searchQuery} placeholder="Type a command or search..." />
      
      <CommandList>
        <CommandEmpty bind:query={searchQuery} />
        
        <CommandGroup heading="File Operations">
          {#each fileCommands as cmd}
            <CommandItem 
              value={cmd.label} 
              action={cmd.action}
              onclick={() => console.log('Clicked:', cmd.label)}
            >
              <div class="command-content">
                <div class="command-label">{cmd.label}</div>
                <div class="command-description">{cmd.description}</div>
              </div>
            </CommandItem>
          {/each}
        </CommandGroup>
        
        <CommandSeparator />
        
        <CommandGroup heading="Extension Commands">
          {#each sampleCommands as cmd}
            <CommandItem 
              value={cmd.label} 
              action={cmd.action}
              onclick={() => console.log('Clicked:', cmd.label)}
            >
              <div class="command-content">
                <div class="command-label">{cmd.label}</div>
                <div class="command-description">{cmd.description}</div>
              </div>
            </CommandItem>
          {/each}
        </CommandGroup>
      </CommandList>
    </Command>
  {/if}

  <div class="test-info">
    <h3>Test Information</h3>
    <p><strong>Selected Value:</strong> {selectedValue || 'None'}</p>
    <p><strong>Search Query:</strong> {searchQuery || 'None'}</p>
    <p><strong>Components Tested:</strong></p>
    <ul>
      <li>✅ Command (with VS Code theming and accessibility)</li>
      <li>✅ CommandInput (with aria attributes)</li>
      <li>✅ CommandList (with listbox role and VS Code theming)</li>
      <li>✅ CommandItem (with IPC integration)</li>
      <li>✅ CommandGroup (with group role and aria-labelledby)</li>
      <li>✅ CommandSeparator (with VS Code theming)</li>
      <li>✅ CommandEmpty (with VS Code theming)</li>
    </ul>
  </div>
</div>

<style>
  .test-container {
    padding: 20px;
    font-family: var(--vscode-font-family);
    color: var(--vscode-foreground);
    background-color: var(--vscode-editor-background);
    min-height: 100vh;
  }

  h2, h3 {
    color: var(--vscode-foreground);
    margin-top: 0;
  }

  .test-controls {
    display: flex;
    gap: 16px;
    align-items: center;
    margin-bottom: 20px;
  }

  .test-controls button {
    background-color: var(--vscode-button-background);
    color: var(--vscode-button-foreground);
    border: none;
    padding: 8px 16px;
    border-radius: 4px;
    cursor: pointer;
    font-family: var(--vscode-font-family);
    font-size: 13px;
  }

  .test-controls button:hover {
    background-color: var(--vscode-button-hoverBackground);
  }

  .status {
    font-size: 12px;
    color: var(--vscode-descriptionForeground);
  }

  .command-content {
    display: flex;
    flex-direction: column;
    gap: 2px;
  }

  .command-label {
    font-weight: 500;
    color: var(--vscode-list-foreground);
  }

  .command-description {
    font-size: 11px;
    color: var(--vscode-descriptionForeground);
  }

  .test-info {
    margin-top: 20px;
    padding: 16px;
    background-color: var(--vscode-textBlockQuote-background);
    border-left: 4px solid var(--vscode-textBlockQuote-border);
    border-radius: 4px;
  }

  .test-info ul {
    margin: 8px 0;
    padding-left: 20px;
  }

  .test-info li {
    margin: 4px 0;
    font-size: 12px;
  }
</style>
