// extension/src/webviews/app/App.svelte
<script lang="ts">
    // P2.2: Main App and Routing
    import { onMount } from 'svelte';
    import appState from './store.svelte.ts';
    import Search from './views/Search.svelte';
    import Settings from './views/Settings.svelte';
    import CommandPaletteTest from './components/CommandPaletteTest.svelte';
    import { hostIpc } from './lib/vscode.ts';
    import { setIpcContext } from './contexts/ipc';
    import {
        SEARCH_METHOD,
        INDEX_STATUS_METHOD,
        LOAD_CONFIG_METHOD,
        CONFIG_DATA_METHOD
    } from '../protocol.ts';
    import type {
        IpcMessage,
        IpcNotification,
        SearchResponseParams,
        IndexStatusParams,
        QdrantOllamaConfig
    } from '../protocol.ts';

    onMount(() => {
        // Set up IPC context for all child components
        setIpcContext(hostIpc);
        
        // Initial Data Fetch
        hostIpc.sendRequest(LOAD_CONFIG_METHOD, 'webview-mgmt', {});

        // Listen for messages from the Extension Host
        const handleMessage = (event: MessageEvent) => {
            const message = event.data as IpcMessage;

            // Security: Validate origin/scope
            if (message.scope !== 'webview-mgmt') return;

            // Fixed: Type guard to safely access params
            // We assume backend messages with payloads are Notifications for these methods
            if (message.kind === 'notification') {
                const notification = message as IpcNotification<any>;

                switch (message.method) {
                    case SEARCH_METHOD:
                        if (notification.params) {
                            const params = notification.params as SearchResponseParams;
                            appState.searchResults = params.results || [];
                        }
                        break;

                    case INDEX_STATUS_METHOD:
                        if (notification.params) {
                            const params = notification.params as IndexStatusParams;
                            appState.indexStatus = params.status;
                            if (params.progress !== undefined) {
                                appState.indexProgress = params.progress;
                            }
                        }
                        break;

                    case CONFIG_DATA_METHOD:
                        appState.config = (notification.params as QdrantOllamaConfig | null) || undefined;
                        break;
                }
            }
        };

        window.addEventListener('message', handleMessage);
        return () => window.removeEventListener('message', handleMessage);
    });
</script>

<main class="h-screen w-screen bg-background text-foreground overflow-hidden font-sans antialiased selection:bg-primary/30">
    <!-- Simple Router Implementation -->
    {#if appState.view === 'search'}
        <Search />
    {:else if appState.view === 'settings'}
        <Settings />
    {:else if appState.view === 'test'}
        <CommandPaletteTest />
    {:else}
        <div class="p-4">Unknown view</div>
    {/if}
</main>

<style>
    :global(body) {
        margin: 0;
        padding: 0;
        overflow: hidden;
    }
</style>

// extension/src/webviews/app/App.tsx
import { useEffect } from 'react';
import { IpcProvider } from './contexts/ipc';
import { hostIpc } from './lib/vscode';
import { useAppStore } from './store';
import {
  SEARCH_METHOD,
  INDEX_STATUS_METHOD,
  LOAD_CONFIG_METHOD,
  CONFIG_DATA_METHOD,
} from '../protocol';
import type {
  IpcMessage,
  IpcNotification,
  SearchResponseParams,
  IndexStatusParams,
  QdrantOllamaConfig,
} from '../protocol';
import Search from './views/Search';
import Settings from './views/Settings';
import CommandPaletteTest from './components/CommandPaletteTest';

export default function App() {
  const view = useAppStore((state) => state.view);
  const setSearchResults = useAppStore((state) => state.setSearchResults);
  const setIndexStatus = useAppStore((state) => state.setIndexStatus);
  const setIndexProgress = useAppStore((state) => state.setIndexProgress);
  const setConfig = useAppStore((state) => state.setConfig);

  useEffect(() => {
    // Initial config load
    hostIpc.sendRequest(LOAD_CONFIG_METHOD, 'webview-mgmt', {}).catch((error) => {
      console.error('Failed to load initial config:', error);
    });

    const handleMessage = (event: MessageEvent) => {
      const message = event.data as IpcMessage;

      if (message.scope !== 'webview-mgmt') return;

      if (message.kind === 'notification') {
        const notification = message as IpcNotification<unknown>;

        switch (message.method) {
          case SEARCH_METHOD: {
            const params = notification.params as SearchResponseParams | undefined;
            if (params) {
              setSearchResults(params.results ?? []);
            }
            break;
          }

          case INDEX_STATUS_METHOD: {
            const params = notification.params as IndexStatusParams | undefined;
            if (params) {
              setIndexStatus(params.status);
              if (typeof params.progress === 'number') {
                setIndexProgress(params.progress);
              }
            }
            break;
          }

          case CONFIG_DATA_METHOD: {
            const cfg = (notification.params as QdrantOllamaConfig | null) ?? undefined;
            setConfig(cfg);
            break;
          }
        }
      }
    };

    window.addEventListener('message', handleMessage);
    return () => window.removeEventListener('message', handleMessage);
  }, [setSearchResults, setIndexStatus, setIndexProgress, setConfig]);

  return (
    <IpcProvider value={hostIpc}>
      <main className="h-screen w-screen bg-background text-foreground overflow-hidden font-sans antialiased selection:bg-primary/30">
        {view === 'search' && <Search />}
        {view === 'settings' && <Settings />}
        {view === 'test' && <CommandPaletteTest />}
        {view !== 'search' && view !== 'settings' && view !== 'test' && (
          <div className="p-4">Unknown view</div>
        )}
      </main>
    </IpcProvider>
  );
}
